### ISSUE TITLE
docke 容器部署，vpn能连接上，但是只能访问到docker容器的ip地址，其他地址无法访问到

### ISSUE THREAD

**Issue by yuantoma** [bjdgyc/anylink#325]
### 使用的anylink版本 ?

<pre>
AnyLink v0.12.1
</pre>

### 使用操作系统的类型和版本?
centos 7.9
</pre>

### 使用linux 内核版本?
<pre>
docker 容器
Linux 154b21fbde37 3.10.0-1160.118.1.el7.x86_64 #1 SMP Wed Apr 24 16:01:50 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

</pre>

连接上sslvpn
![image](https://github.com/bjdgyc/anylink/assets/141614242/83091450-a06c-4085-9198-007ec2057155)
172.17.0.2 这个地址可以通，但是192.168.31.1就不通过，也配置过其余的比如百度www.baidu.com也不通就只通docker 容器的ip

docker 容器:
![image](https://github.com/bjdgyc/anylink/assets/141614242/804e54c6-bc21-416c-ae5f-2883ff40c9c1)
![image](https://github.com/bjdgyc/anylink/assets/141614242/eedc5ef5-bd72-4e9f-b8d0-fbb8592d37e6)
宿主机:
![image](https://github.com/bjdgyc/anylink/assets/141614242/0c767aa6-8722-438c-ad5f-6e21a15e7a98)

**Comment by bjdgyc** [comment]
使用官方镜像

**Comment by zisain** [comment]
容器内部没有开启转发吧?

**Comment by yeruyi1024** [comment]
刚部署完，我用compose启动的，一切正常，看看是不是内核吧，我记得有个issue说如果低于多少要开 IPTABLES_LEGACY: "on"

```
services:
  anylink:
    image: registry.cn-hangzhou.aliyuncs.com/bjdgyc/anylink:latest
    container_name: anylink
    restart: always
    privileged: true
    #cpus: 2
    #mem_limit: 4g
    ports:
      - 443:443
      - 8800:8800
      - 443:443/udp
    environment:
      LINK_LOG_LEVEL: info
      IPTABLES_LEGACY: "on"
    command:
      - --conf=/app/conf/server.toml
    volumes:
      - ./conf:/app/conf
    dns_search: .
    sysctls:
      net.ipv4.ip_forward: 1
```
